// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD5aScXQywqXaf0IHLdPuVbZ0LL2wwOqU',
    appId: '1:644977806142:web:340833b0db6d1b59acba6f',
    messagingSenderId: '644977806142',
    projectId: 'kubiec-scada-notifi',
    authDomain: 'kubiec-scada-notifi.firebaseapp.com',
    storageBucket: 'kubiec-scada-notifi.firebasestorage.app',
    measurementId: 'G-HBD12TJZVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5BgTJa-tW7PEwny6qRcWeSwuVdk_TA18',
    appId: '1:644977806142:android:698028424a9d4b96acba6f',
    messagingSenderId: '644977806142',
    projectId: 'kubiec-scada-notifi',
    storageBucket: 'kubiec-scada-notifi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy70k_qRKLm64WNkNGwKb93YJrlVhX3o8',
    appId: '1:644977806142:ios:d1a040e4fa7b250dacba6f',
    messagingSenderId: '644977806142',
    projectId: 'kubiec-scada-notifi',
    storageBucket: 'kubiec-scada-notifi.firebasestorage.app',
    iosBundleId: 'com.example.proyectoscada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy70k_qRKLm64WNkNGwKb93YJrlVhX3o8',
    appId: '1:644977806142:ios:d1a040e4fa7b250dacba6f',
    messagingSenderId: '644977806142',
    projectId: 'kubiec-scada-notifi',
    storageBucket: 'kubiec-scada-notifi.firebasestorage.app',
    iosBundleId: 'com.example.proyectoscada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD5aScXQywqXaf0IHLdPuVbZ0LL2wwOqU',
    appId: '1:644977806142:web:340833b0db6d1b59acba6f',
    messagingSenderId: '644977806142',
    projectId: 'kubiec-scada-notifi',
    authDomain: 'kubiec-scada-notifi.firebaseapp.com',
    storageBucket: 'kubiec-scada-notifi.firebasestorage.app',
    measurementId: 'G-HBD12TJZVY',
  );

}